name: Snake Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PIL
      run: pip install Pillow

    - name: Generate Snake GIF
      run: python snake.py

    - name: Upload Snake GIF
      uses: actions/upload-artifact@v2
      with:
        name: snake.gif
        path: snake.gif

    - name: Update README
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./
        force_orphan: true
