name: Generate Datas

on:
  schedule: # execute every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: barretot
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages
        run: |
          git remote add pages-remote https://$GITHUB_ACTOR:$PAT_TOKEN@github.com/barretot/barretot.git
          git push -f pages-remote output
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
