name: Snake Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PIL
        run: pip install Pillow

      - name: Generate Snake GIF
        run: python snake.py

      - name: Upload Snake GIF
        uses: actions/upload-artifact@v2
        with:
          name: snake.gif
          path: snake.gif

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Snake GIF
        uses: actions/download-artifact@v2
        with:
          name: snake.gif
          path: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./
          force_orphan: true
